language: node_js
node_js:
  - stable
install:
  - npm install --g lerna
  - lerna bootstrap

script:
  - lerna run test

# Send coverage data to Coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
